sylius_cart:
    classes:
        item:
            controller: EzSylius\Sylius\CoreBundle\Controller\CartItemController


sylius_product:
    classes:
        product:
            model: EzSylius\Sylius\CoreBundle\Entity\Product
            form:
                default: EzSylius\Sylius\CoreBundle\Form\Type\ProductType
