<?php
/**
 * Autoloader definition for eZ Publish Extension files.
 *
 * @copyright Copyright (C) eZ Systems AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 * @version //autogentag//
 * @package kernel
 *
 */

return array(
      'EnchantSpell'                        => 'extension/ezoe/modules/ezoe/classes/EnchantSpell.php',
      'GoogleSpell'                         => 'extension/ezoe/modules/ezoe/classes/GoogleSpell.php',
      'Moxiecode_JSON'                      => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'Moxiecode_JSONReader'                => 'extension/ezoe/modules/ezoe/classes/utils/mcejson.php',
      'NgSymfonyToolsApiContentConverter'   => 'extension/ngsymfonytools/classes/ngsymfonytoolsapicontentconverter.php',
      'NgSymfonyToolsControllerOperator'    => 'extension/ngsymfonytools/classes/ngsymfonytoolscontrolleroperator.php',
      'NgSymfonyToolsIncludeOperator'       => 'extension/ngsymfonytools/classes/ngsymfonytoolsincludeoperator.php',
      'NgSymfonyToolsPathUrlOperator'       => 'extension/ngsymfonytools/classes/ngsymfonytoolspathurloperator.php',
      'NgSymfonyToolsRenderOperator'        => 'extension/ngsymfonytools/classes/ngsymfonytoolsrenderoperator.php',
      'PSpell'                              => 'extension/ezoe/modules/ezoe/classes/PSpell.php',
      'PSpellShell'                         => 'extension/ezoe/modules/ezoe/classes/PSpellShell.php',
      'SpellChecker'                        => 'extension/ezoe/modules/ezoe/classes/SpellChecker.php',
      'SyliusProduct'                       => 'extension/ngsyliusproduct/datatypes/syliusproduct/syliusproduct.php',
      'SyliusProductType'                   => 'extension/ngsyliusproduct/datatypes/syliusproduct/syliusproducttype.php',
      'eZArchive'                           => 'extension/ezdemo/autoloads/ezarchive.php',
      'eZCreateClassListGroups'             => 'extension/ezwt/autoloads/ezcreateclasslistgroups.php',
      'eZFeedReader'                        => 'extension/ezflow/autoloads/ezfeedreader.php',
      'eZFlowAjaxContent'                   => 'extension/ezflow/classes/ezflowajaxcontent.php',
      'eZFlowBlock'                         => 'extension/ezflow/classes/ezflowblock.php',
      'eZFlowFetchInterface'                => 'extension/ezflow/classes/ezflowfetchinterface.php',
      'eZFlowFunctionCollection'            => 'extension/ezflow/modules/ezflow/functioncollection.php',
      'eZFlowKeywordsFetch'                 => 'extension/ezflow/classes/fetches/ezflowkeywordsfetch.php',
      'eZFlowLatestContent'                 => 'extension/ezflow/classes/fetches/ezflowlatestcontent.php',
      'eZFlowLatestObjects'                 => 'extension/ezflow/classes/fetches/ezflowlatestobjects.php',
      'eZFlowMCFetch'                       => 'extension/ezflow/classes/fetches/ezflowmcfetch.php',
      'eZFlowOperations'                    => 'extension/ezflow/classes/ezflowoperations.php',
      'eZFlowPool'                          => 'extension/ezflow/classes/ezflowpool.php',
      'eZFlowPoolItem'                      => 'extension/ezflow/classes/ezflowpoolitem.php',
      'eZFlowServerCallFunctions'           => 'extension/ezflow/classes/ezflowservercallfunctions.php',
      'eZGmapLocation'                      => 'extension/ezgmaplocation/classes/ezgmaplocation.php',
      'eZGmapLocationType'                  => 'extension/ezgmaplocation/datatypes/ezgmaplocation/ezgmaplocationtype.php',
      'eZHTTPCacheManager'                  => 'extension/ezflow/classes/ezhttpcachemanager.php',
      'eZHTTPCacheManagerInterface'         => 'extension/ezflow/classes/ezhttpcachemanagerinterface.php',
      'eZIEEzcConversions'                  => 'extension/ezie/classes/interfaces/conversions.php',
      'eZIEEzcGDHandler'                    => 'extension/ezie/classes/handlers/gd.php',
      'eZIEEzcImageMagickHandler'           => 'extension/ezie/classes/handlers/magick.php',
      'eZIEImageAction'                     => 'extension/ezie/classes/image_action.php',
      'eZIEImageAnalyzer'                   => 'extension/ezie/classes/image_analyzer.php',
      'eZIEImageFilterBW'                   => 'extension/ezie/classes/image_filter_bw.php',
      'eZIEImageFilterBrightness'           => 'extension/ezie/classes/image_filter_brightness.php',
      'eZIEImageFilterContrast'             => 'extension/ezie/classes/image_filter_contrast.php',
      'eZIEImageFilterSepia'                => 'extension/ezie/classes/image_filter_sepia.php',
      'eZIEImagePreAction'                  => 'extension/ezie/classes/image_pre_action.php',
      'eZIEImageToolCrop'                   => 'extension/ezie/classes/image_tool_crop.php',
      'eZIEImageToolFlipHorizontally'       => 'extension/ezie/classes/image_tool_flip_horizontally.php',
      'eZIEImageToolFlipVertically'         => 'extension/ezie/classes/image_tool_flip_vertically.php',
      'eZIEImageToolPixelate'               => 'extension/ezie/classes/image_tool_pixelate.php',
      'eZIEImageToolResize'                 => 'extension/ezie/classes/image_tool_resize.php',
      'eZIEImageToolRotation'               => 'extension/ezie/classes/image_tool_rotation.php',
      'eZIEImageToolWatermark'              => 'extension/ezie/classes/image_tool_watermark.php',
      'eZIEezcImageConverter'               => 'extension/ezie/classes/image_converter.php',
      'eZJSON'                              => 'extension/ezflow/autoloads/ezjson.php',
      'eZKeywordList'                       => 'extension/ezdemo/autoloads/ezkeywordlist.php',
      'eZMultiuploadHandler'                => 'extension/ezmultiupload/classes/ezmultiuploadhandler.php',
      'eZMultiuploadHandlerInterface'       => 'extension/ezmultiupload/classes/ezmultiuploadhandlerinterface.php',
      'eZOEInputParser'                     => 'extension/ezoe/ezxmltext/handlers/input/ezoeinputparser.php',
      'eZOETemplateUtils'                   => 'extension/ezoe/autoloads/ezoetemplateutils.php',
      'eZOEXMLInput'                        => 'extension/ezoe/ezxmltext/handlers/input/ezoexmlinput.php',
      'eZOOConverter'                       => 'extension/ezodf/classes/ezooconverter.php',
      'eZOOGenerator'                       => 'extension/ezodf/classes/ezoogenerator.php',
      'eZOOImport'                          => 'extension/ezodf/classes/ezooimport.php',
      'eZOpenofficeUploadHandler'           => 'extension/ezodf/uploadhandlers/ezopenofficeuploadhandler.php',
      'eZPaEx'                              => 'extension/ezmbpaex/classes/ezpaex.php',
      'eZPaExUser'                          => 'extension/ezmbpaex/login_handler/ezpaexuser.php',
      'eZPage'                              => 'extension/ezflow/classes/ezpage.php',
      'eZPageBlock'                         => 'extension/ezflow/classes/ezpageblock.php',
      'eZPageBlockItem'                     => 'extension/ezflow/classes/ezpageblockitem.php',
      'eZPageData'                          => 'extension/ezdemo/autoloads/ezpagedata.php',
      'eZPageLink'                          => 'extension/ezflow/autoloads/ezpagelink.php',
      'eZPageSwapType'                      => 'extension/ezflow/eventtypes/event/ezpageswap/ezpageswaptype.php',
      'eZPageType'                          => 'extension/ezflow/datatypes/ezpage/ezpagetype.php',
      'eZPageZone'                          => 'extension/ezflow/classes/ezpagezone.php',
      'eZRESTODFHandler'                    => 'extension/ezodf/classes/ezrestodfhandler.php',
      'eZRed5StreamListOperator'            => 'extension/ezflow/autoloads/ezred5streamlist.php',
      'eZSquidCacheManager'                 => 'extension/ezflow/classes/ezsquidcachemanager.php',
      'eZSyliusFunctionCollection'          => 'extension/ngsyliusproduct/modules/sylius/ezsyliusfunctioncollection.php',
      'eZTagCloud'                          => 'extension/ezdemo/autoloads/eztagcloud.php',
      'eZUnserialize'                       => 'extension/ezflow/autoloads/ezunserialize.php',
      'ezgmlLocationFilter'                 => 'extension/ezgmaplocation/classes/ezgmllocationfilter.php',
      'ezjscAccessTemplateFunctions'        => 'extension/ezjscore/autoloads/ezjscaccesstemplatefunctions.php',
      'ezjscAjaxContent'                    => 'extension/ezjscore/classes/ezjscajaxcontent.php',
      'ezjscCacheManager'                   => 'extension/ezjscore/classes/ezjsccachemanager.php',
      'ezjscCssOptimizer'                   => 'extension/ezjscore/classes/ezjsccssoptimizer.php',
      'ezjscEncodingTemplateFunctions'      => 'extension/ezjscore/autoloads/ezjscencodingtemplatefunctions.php',
      'ezjscJavascriptOptimizer'            => 'extension/ezjscore/classes/ezjscjavascriptoptimizer.php',
      'ezjscPacker'                         => 'extension/ezjscore/classes/ezjscpacker.php',
      'ezjscPackerTemplateFunctions'        => 'extension/ezjscore/autoloads/ezjscpackertemplatefunctions.php',
      'ezjscServerFunctions'                => 'extension/ezjscore/classes/ezjscserverfunctions.php',
      'ezjscServerFunctionsAjaxUploader'    => 'extension/ezjscore/classes/ezjscserverfunctionsajaxuploader.php',
      'ezjscServerFunctionsAutosave'        => 'extension/ezautosave/classes/ezjscserverfunctionsautosave.php',
      'ezjscServerFunctionsJs'              => 'extension/ezjscore/classes/ezjscserverfunctionsjs.php',
      'ezjscServerFunctionsNode'            => 'extension/ezjscore/classes/ezjscserverfunctionsnode.php',
      'ezjscServerFunctionsPublishingQueue' => 'extension/ezjscore/classes/ezjscserverfunctionspublishingqueue.php',
      'ezjscServerRouter'                   => 'extension/ezjscore/classes/ezjscserverrouter.php',
      'ezoeServerFunctions'                 => 'extension/ezoe/classes/ezoeserverfunctions.php',
      'ezpAjaxUploaderHandlerInterface'     => 'extension/ezjscore/classes/ajaxuploader/ezpajaxuploaderhandlerinterface.php',
      'ezpRelationAjaxUploader'             => 'extension/ezjscore/classes/ajaxuploader/ezprelationajaxuploader.php',
      'ezpRelationListAjaxUploader'         => 'extension/ezjscore/classes/ajaxuploader/ezprelationlistajaxuploader.php',
      'ezpRestApiProvider'                  => 'extension/ezprestapiprovider/classes/rest_provider.php',
      'ezpRestApiViewController'            => 'extension/ezprestapiprovider/classes/view_controller.php',
      'ezpRestAtomController'               => 'extension/ezprestapiprovider/classes/controllers/atom.php',
      'ezpRestAtomDecorator'                => 'extension/ezprestapiprovider/classes/views/atom_decorator.php',
      'ezpRestAtomView'                     => 'extension/ezprestapiprovider/classes/views/atom.php',
      'ezpRestContentController'            => 'extension/ezprestapiprovider/classes/controllers/content.php',
      'ezpRestContentModel'                 => 'extension/ezprestapiprovider/classes/models/rest_content_model.php',
      'ezpaextype'                          => 'extension/ezmbpaex/datatypes/ezpaex/ezpaextype.php',
      'ezsrRatingDataObject'                => 'extension/ezstarrating/classes/ezsrratingdataobject.php',
      'ezsrRatingFilter'                    => 'extension/ezstarrating/classes/ezsrratingfilter.php',
      'ezsrRatingObject'                    => 'extension/ezstarrating/classes/ezsrratingobject.php',
      'ezsrRatingObjectTreeNode'            => 'extension/ezstarrating/classes/ezsrratingobjecttreenode.php',
      'ezsrRatingType'                      => 'extension/ezstarrating/datatypes/ezsrrating/ezsrratingtype.php',
      'ezsrServerFunctions'                 => 'extension/ezstarrating/classes/ezsrserverfunctions.php',
      'ezsrTemplateOperators'               => 'extension/ezstarrating/autoloads/ezsrtemplateoperators.php',
      'ezwtServerCallFunctions'             => 'extension/ezwt/classes/ezwtservercallfunctions.php',
      'ezxFormToken'                        => 'extension/ezformtoken/event/ezxformtoken.php',
      'ngsymfonytoolsInfo'                  => 'extension/ngsymfonytools/ezinfo.php',
    );

?>
